name: Web regular AppService

on:
  push:
    branches:
      - main
env:
  CI: false
  AZURE_WEBAPP_NAME: devopswithgithub-carmenc-13af2    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'd:\a\TailwindTraders-Website-Demo-Drop'    
  AZURE_WEBAPP_PROJECT_PATH_CLIENTAPP: 'd:\a\TailwindTraders-Website-Demo\TailwindTraders-Website-Demo\Source\Tailwind.Traders.Web\ClientApp'
  AZURE_WEBAPP_PROJECT_PATH: 'd:\a\TailwindTraders-Website-Demo\TailwindTraders-Website-Demo\Source\Tailwind.Traders.Web'
  #AZURE_WEBAPP_PROJECT_PATH: 'd:\a\TailwindTraders-Website\TailwindTraders-Website\Source\Tailwind.Traders.Web\Tailwind.Traders.Web.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    #- uses: azure/login@v1
      #with:
        #creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.3

    - name: Install dependencies in client app
      working-directory: ${{ env.AZURE_WEBAPP_PROJECT_PATH_CLIENTAPP }}
      run: npm install

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101 #2.1.400

    - name: Build with dotnet
      working-directory: ${{ env.AZURE_WEBAPP_PROJECT_PATH }}
      run: dotnet build --configuration Release --verbosity Detailed

    - name: dotnet publish
      working-directory: Source/Tailwind.Traders.Web
      run: |
        dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PROJECT_PATH }} --verbosity Detailed

    #- uses: azure/appservice-settings@v1
      #with:
        #app-name: ${{ secrets.WEBAPP_APPSERVICE_NAME }}
        #app-settings-json: '${{ secrets.WEBAPP_APP_SETTINGS }}'

    - name: Run Azure webapp deploy action
      uses: azure/webapps-deploy@v1
      with: 
        #app-name: ${{ secrets.WEBAPP_APPSERVICE_NAME }}
        #package: ${{env.DOTNET_ROOT}}/Source/Tailwind.Traders.Web
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TailwindtradersSecret }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    #- name: Azure logout
      #run: |
        #az logout
